config/routes.rb
Rails.application.routes.draw do
  resources :autores
  get 'paginas/index'

  get 'paginas/funcionarios'

  get 'paginas/clientes'

  get 'paginas/livros'

  root 'paginas#index'

  resources :livros
  resources :clientes
  resources :funcionarios do
collection do
get :listar
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	validates_presence_of :nome, message: "O nome deve ser preenchido"
	validates_presence_of :matricula, message: "A matrícula deve ser preenchido"
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]



  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  def index
    @pnome = params[:pnome]
    filtro = "1=1"
    if (@pnome)
      filtro = filtro + " and nome like '%"+@pnome.strip+"%'"
    end  
    @clientes = Cliente.where(filtro).order("nome").paginate(page:
      params[:page], per_page: 3)
  end
  
  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:matricula, :nome, :endereco, :telefone, :email, :cpf, :livros_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(cliente) do |f| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %>
    <%= f.text_field :matricula %>
  </div>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_field :endereco %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', clientes_path , class: "btn btn-default " %>
  </div>
<% end %>

app/views/clientes/_formbusca.html.erb
<%= form_tag(clientes_path, method: "get") do %>
	<%= label_tag(:pnome, "Nome:") %>
	<%= text_field_tag(:pnome, @pnome) %>
	<%= submit_tag 'Filtrar' %> 
<% end %>	

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>
<hr/>
<%= render 'formbusca' %>
<hr/>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.matricula %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.cpf %></td>
        <td><%= link_to ' ', cliente , class: "glyphicon glyphicon-blackboard" %></td>
        <td><%= link_to ' ', edit_cliente_path(cliente), class: "glyphicon glyphicon-pencil"%></td> 
        <td><%= link_to ' ', cliente, method: :delete, data: { confirm: 'Deseja Realmente Excluir?' }, class:"glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>
<%= will_paginate @funcionarios, previous_label: "Anterior", next_label: "Próxima" %>
<br/>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @cliente.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>