config/routes.rb
Rails.application.routes.draw do
  resources :autores
  get 'paginas/index'

  get 'paginas/funcionarios'

  get 'paginas/clientes'

  get 'paginas/livros'

  root 'paginas#index'

  resources :livros
  resources :clientes
  resources :funcionarios do
collection do
get :listar
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
	validates_presence_of :nome, message: "O nome deve ser preenchido"
	validates_presence_of :matricula, message: "A matrícula deve ser preenchido"
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  def index
    @pnome = params[:pnome]
    filtro = "1=1"
    if not(@pnome.nil?)
      filtro = filtro + " and nome like '%"+@pnome+"%'"
    end 
    @funcionarios = Funcionario.where(filtro).order("nome").paginate(page:
      params[:page], per_page: 3) 
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def listar

    @funcionarios = Funcionario.all.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.pdf do
        pdf = FuncionariosReport.new(@funcionarios)
        send_data pdf.render, filename: 'FuncionariosListagem.pdf', :width => pdf.bounds.width,
        type: 'application/pdf', disposition: :inline, :page_size => "A4", :page_layout => :portrait
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:matricula, :nome, :endereco, :telefone, :email, :cargo, :dtadmissao)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(funcionario) do |f| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %>
    <%= f.text_field :matricula %>
  </div>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_field :endereco %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :cargo %>
    <%= f.text_field :cargo %>
  </div>

  <div class="field">
    <%= f.label "Data de Admissão" %><br>
    <%= f.text_field :dtadmissao , class: 'datepicker' %>
  </div>
  
  
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', funcionarios_path , class: "btn btn-default " %>
  </div>
  </div>
  <% end %>

  <script type="text/javascript">
  $(document).ready(function(){
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  $('#matricula').inputmask("9999.9.999.9999");
  });
  </script>  

app/views/funcionarios/_formbusca.html.erb
<%= form_tag(funcionarios_path, method: "get") do %>
	<%= label_tag(:pnome, "Nome:") %>
	<%= text_field_tag(:pnome, @pnome) %>
	<%= submit_tag 'Filtrar' %>
<% end %>	

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

  <hr/>
  <%= render 'formbusca' %>
  <hr/>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Cargo</th>
      <th>Data Admissão</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.matricula %></td>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.cargo %></td>
        <td><%= funcionario.dtadmissao %></td>
        <td><%= link_to ' ', funcionario , class: "glyphicon glyphicon-blackboard"%></td>
        <td><%= link_to ' ', edit_funcionario_path(funcionario), class: "glyphicon glyphicon-pencil"%></td>
        <td><%= link_to ' ', funcionario, method: :delete, data: { confirm: 'Are you sure?' }, class:"glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>
<%= will_paginate @funcionarios, previous_label: "Anterior", next_label: "Próxima" %>
<br/>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @funcionario.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @funcionario.cargo %>
</p>

<p>
  <strong>Data Admissão:</strong>
  <%= @funcionario.dtadmissao %>
</p>


<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>