config/routes.rb
Rails.application.routes.draw do
  resources :autores
  get 'paginas/index'

  get 'paginas/funcionarios'

  get 'paginas/clientes'

  get 'paginas/livros'

  root 'paginas#index'

  resources :livros
  resources :clientes
  resources :funcionarios do
collection do
get :listar
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/livro.rb
class Livro < ActiveRecord::Base

	validates_presence_of :titulo, message: "O título deve ser preenchido"
	validates_presence_of :codigo, message: "O código deve ser preenchido"
	mount_uploader :capa, CapaLivroUploader
	belongs_to :autor
	
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  def index
    @ptitulo = params[:ptitulo]

    filtro = "1=1"

    if not(@ptitulo.nil?)
      filtro = filtro + " and titulo like '%"+@ptitulo+"%'"
    end  

    @livros = Livro.where(filtro).order("titulo").paginate(page:
      params[:page], per_page: 3)
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:codigo, :titulo, :autor_id, :editora, :preco, :capa)
    end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form.html.erb
<%= form_for(livro) do |f| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :editora %>
    <%= f.text_field :editora %>
  </div>

  <div class="field">
    <%= f.label :preco %>
    <%= f.text_field :preco %>
  </div>

  <div>
    <%= f.label :capa %>
    <%= image_tag @livro.capa_url, class: 'capa' if @livro.capa? %>
    <%= f.file_field :capa, label: 'Capa' , input_html: {accept: ('application/jpg') } %>
    <br/>
  </div>

  <div class="field">
    <%= f.label :autor %><br>
    <%= f.select :autor_id, options_for_select(Autor.all.map{|m|[m.nome,
    m.id]},f.object.autor_id) %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', livros_path , class: "btn btn-default " %>
  </div>
<% end %>

app/views/livros/_formbusca.html.erb
<%= form_tag(livros_path, method: "get") do %>
	<%= label_tag(:ptitulo, "Titulo:") %>
	<%= text_field_tag(:ptitulo, @ptitulo) %>
	<%= submit_tag 'Filtrar'  %>
<% end %>	

app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Livros</h1>

  <hr/>
  <%= render 'formbusca' %>
  <hr/>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Editora</th>
      <th>Preco</th>
      <th>Capa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.codigo %></td>
        <td><%= livro.titulo %></td>
        <td><%= livro.autor.nome if livro.autor %></td>
        <td><%= livro.editora %></td>
        <td>R$ <%= livro.preco %></td>
        <td><%= image_tag livro.capa, height:'80', width:'62' %></td> 
        <td><%= link_to ' ', livro , class: "glyphicon glyphicon-blackboard" %></td>
        <td><%= link_to ' ', edit_livro_path(livro) , class: "glyphicon glyphicon-pencil"%></td>
        <td><%= link_to ' ', livro, method: :delete, data: { confirm: 'Deseja Realmente Excluir?' }, class:"glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Livro', new_livro_path %>
<%= will_paginate @livros, previous_label: "Anterior", next_label: "Próxima" %>
<br/>

app/views/livros/new.html.erb
<h1>New Livro</h1>

<%= render 'form', livro: @livro %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @livro.codigo %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor.nome %>
</p>

<p>
  <strong>Editora:</strong>
  <%= @livro.editora %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @livro.preco %>
</p>

<%= link_to 'Edit', edit_livro_path(@livro) %> |
<%= link_to 'Back', livros_path %>