config/routes.rb
Rails.application.routes.draw do
  resources :autores
  get 'paginas/index'

  get 'paginas/funcionarios'

  get 'paginas/clientes'

  get 'paginas/livros'

  root 'paginas#index'

  resources :livros
  resources :clientes
  resources :funcionarios do
collection do
get :listar
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_latbar.html.erb
<div id="wrapper">
	<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
	<li class="sidebar-brand">
		<a href="#" >
			<h4><%= link_to 'Menu', paginas_index_path %></h4>
		</a>
	</li>
<li style="font-size: 20px;">
	<%= link_to ' Cliente', clientes_path,
	class: "glyphicon glyphicon-user" %>
</li>
<br/>
<li style="font-size: 20px;">
	<%= link_to ' Autor', autores_path,
	class: "glyphicon glyphicon-user" %>
</li>
<br/>
<li style="font-size: 20px;">
	<%= link_to ' Livros', livros_path ,
	class: "glyphicon glyphicon-book"%>
</li>
<br/>
<li style="font-size: 20px;">
	<%= link_to ' Funcionário', funcionarios_path ,
	class: "glyphicon glyphicon-user"%>
</li>
<br/>
<li style="font-size: 20px;">
        <%= link_to " Relatorio", listar_funcionarios_path(@funcionario,  :format => 'pdf'), target: '_blank', class: "glyphicon glyphicon-print" %> 
</li>
</ul>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
    <img class="logo" src="/assets/logo.png">
      <a href> Cadmun Books </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadmun Books</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render "layouts/navbar" %>

	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "layouts/latbar" %>
			</div>
			<div class="col-md-9">
				<div class="panel-body">
					<%= yield %>
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>

				</div>
			</div>
		</div> <!-- row -->
	</div> <!-- container -->

  
  </body>
</html>